#!/usr/bin/env node
var cp = require('./utils/child-process-wrapper.js');
var path = require('path');

process.chdir(path.dirname(__dirname));

cp.safeExec.bind(global, 'npm install npm --loglevel error', {cwd: path.resolve(__dirname, '..', 'build')}, function() {
  cp.safeExec.bind(global, 'node script/install', function(error) {
    if (error)
      process.exit(1);

    var async = require('async');
    var gruntPath = path.join('build', 'node_modules', '.bin', 'grunt') + (process.platform === 'win32' ? '.cmd' : '');
    var tasks = [
      cp.safeExec.bind(global, 'git clean -dff'),
      cp.safeExec.bind(global, gruntPath + ' ci --gruntfile build/Gruntfile.coffee --stack --no-color'),
    ]
    async.series(tasks, function(error) {
      process.exit(error ? 1 : 0);
    });
  })();
})();